services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:80
  #   environment:
  #     - REACT_APP_API_URL=http://localhost/api
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - gateway

  gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ENABLE_SCALAR=true
    depends_on:
      # - goservice
      # - flask
      - auth
    networks:
      - mynetwork
    volumes:
      - ~/.aspnet/https:/https:ro

  auth:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ENABLE_SCALAR=true
    depends_on:
      - db_manager
    networks:
      - mynetwork

  db_manager:
    build:
      context: .
      dockerfile: DatabaseManager/Dockerfile
    ports:
      - 8090:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ENABLE_SCALAR=true
    depends_on:
      - database
    networks:
      - mynetwork

  goservice:
    build:
      context: ./go
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  fast_api:
    build:
      context: ./fast_api
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - 7070:8000
    depends_on:
      - database
      - rabbitmq

  spring:
    build:
      context: ./JavaService
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - 2020:8080
    depends_on:
      - database

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - 7000:9000
    volumes:
      - ./laravel:/var/www
    depends_on:
      - database
  js_express:
    build:
      context: ./js_express
      dockerfile: Dockerfile
    networks:
      - mynetwork
    ports:
      - 6713:6713
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    depends_on:
      - database
    networks:
      - mynetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  database:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword123!
      POSTGRES_DB: project
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - mynetwork
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000 # API MinIO (S3)
      - 9090:9090 # MinIO Console (UI)
    environment:
      MINIO_ROOT_USER: admin # Wymagana nazwa użytkownika (login)
      MINIO_ROOT_PASSWORD: admin123 # Wymagane hasło (min. 8 znaków)
      MINIO_SERVER_URL: http://localhost:9000 # URL do serwera
      MINIO_CONSOLE_ADDRESS: ":9090" # Adres dla interfejsu webowego
    volumes:
      - minio_data:/data # Przechowywanie danych
    command: server /data --console-address ":9090"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
  minio_data:
